version: '3.8'
services:
  gatsby-starter-default:
    image: node:22
    container_name: gatsby-starter-default
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install --silent && npm run dev -- --host 0.0.0.0"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
